import { CareerProps } from '../types/careers';

export const CAREERS: CareerProps[] = [
  {
    position: 'BIM Consultant',
    company: 'SENBIM',
    company_legal_name: 'SENBIM',
    logo: null,
    location: 'Taiwan 🇹🇼',
    location_type: 'Remote',
    type: 'Co-founder',
    start_date: '2025-06',
    end_date: null,
    industry: 'construction technology',
    link: null,
    responsibilities: [
      'Founded and lead SENBIM, delivering BIM services and consulting for AEC teams operating in the U.S. and Africa.',
      'Scan-to-BIM: convert point cloud and photogrammetry data into accurate Revit models and drawing sets.',
      'BIM coordination & clash detection: facilitate collaboration across disciplines and produce clash reports using Navisworks/Revit.',
      'Architectural, structural, and MEP modeling for design coordination and as-built documentation.',
      'Construction technology consulting on BIM adoption, workflows, and digital delivery standards.',
      'Delivered projects across residential, commercial, hospitals, education, airports, stadiums, and renovation work with a focus on accuracy and client satisfaction.',
    ],
  },
  {
    position: 'Senior BIM/VDC Specialist',
    company: 'JE Dunn',
    company_legal_name: 'JE Dunn',
    logo: null,
    location: 'United States 🇺🇸',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2022-10',
    end_date: '2025-06',
    industry: 'construction',
    link: null,
    responsibilities: [
      'Led VDC efforts overseeing MEP coordination including cleanrooms, sub-fabs, and central utility buildings.',
      'Integrated and managed federated 3D models using Navisworks Manage, Revit, and BIM 360/ACC; drove weekly clash detection and issue resolution across trades.',
      'Coordinated 3D point clouds for accurate as-built documentation and QA/QC validation.',
      'Organized and led BIM coordination meetings; documented action items and ensured model deliverables met milestone deadlines.',
      'Provided technical training to field engineers on BIM and digital workflows.',
      'Aligned VDC strategy with BIM Execution Plans (BxPs) and ensured compliance and delivery consistency.',
      'Managed trade partner model validation, version control, and model health checks to maintain data integrity and LOD compliance.',
    ],
  },
  {
    position: 'Senior VDC Specialist',
    company: 'Viateknik',
    company_legal_name: 'Viateknik',
    logo: null,
    location: 'United States 🇺🇸',
    location_type: 'Onsite',
    type: 'Full-time',
    start_date: '2021-06',
    end_date: '2022-02',
    industry: 'engineering',
    link: null,
    responsibilities: [
      'BIM coordination for Mechanical, Electrical, and Plumbing (MEP) design models.',
      'Created as-built 3D models.',
      'Supported facility management and building operations using BIM tools.',
    ],
  },
];
